name: Build and Deploy App

on:
  push:
    branches: [ "main" ]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=So-fire_three_tier_with_sonarcube  
            -Dsonar.organization=so-fire
          #ALWAYS MAKE SURE YOU INPUT YOUR SONARCUBE PROJECT NAME AND ORG IN TE TWO CODES ABOVE # 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_push:
    needs: sonar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set DockerHub Username as Environment Variable
        run: echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV

      - name: Build and Push via Docker Compose
        run: docker compose build && docker compose push

      
      # - name: Build Docker Image
      #   run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fintech-app:latest .

      # - name: Push Docker Image
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fintech-app:latest
